# Generated by Django 4.1.6 on 2023-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_finished_time_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
