# Generated by Django 4.1.6 on 2023-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.FileField(max_length=20, null=True, upload_to=''),
        ),
    ]
